### ISSUE TITLE
Bundling breaks relative references in stylesheets

### ISSUE THREAD

**Issue by georged** [funnelweblog/FunnelWeb#28]
Some of the stylesheets include relative references to the static files, e.g. in \Content\themes\base\Base.css

``` css
a.new-window
{
    background: transparent url('../../Images/external.png') no-repeat scroll right center;
    padding: 0 13px 0 0;
}
```

Before bundling, _Base.css_ was included as "~/Content/themes/base/Base.css" and image path was therefore "~/Content/Images/external.png". Bundling shortens URL

``` cs
bundles.Add(new StyleBundle("~/Content/css").Include("~/Content/themes/base/Base.css"));
```

That makes image path to be "~/Content/../../Images/external.png" which is obviously wrong. The easiest solution is probably to artificially extend the bundled path to match previous folder structure, e.g.

``` cs
bundles.Add(new StyleBundle("~/Content/themes/base/css").Include("~/Content/themes/base/Base.css"));
```
